'use client';

import { FormEvent } from 'react';
import { ArrowLeft, ArrowRight, Plus, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { COLORS } from './types';
import { Field } from './field';

export function HostForm({ username, setUsername, marketTitle, setMarketTitle, customCode, setCustomCode, closesAt, setClosesAt, labels, setLabels, onSubmit, error, back }: { username: string; setUsername: (v: string) => void; marketTitle: string; setMarketTitle: (v: string) => void; customCode: string; setCustomCode: (v: string) => void; closesAt: string; setClosesAt: (v: string) => void; labels: string[]; setLabels: (v: string[]) => void; onSubmit: (e: FormEvent) => void; error: string; back: () => void }) {
  return <section className="mx-auto max-w-2xl px-5 py-10 md:px-10"><Button variant="ghost" onClick={back} className="mb-5"><ArrowLeft /> Back</Button><form onSubmit={onSubmit} className="rounded-[2rem] border bg-card p-6 shadow-sm md:p-9"><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">New bet</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">What will everyone predict?</h1><div className="mt-8 grid gap-5"><Field label="Your name"><Input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="e.g. Brandon" className="h-11" maxLength={24} /></Field><Field label="Prediction question"><Input value={marketTitle} onChange={(e) => setMarketTitle(e.target.value)} placeholder="e.g. Who will win game night?" className="h-11" maxLength={90} /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Custom bet code (optional)"><Input value={customCode} onChange={(e) => setCustomCode(e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g, ''))} placeholder="GAME-NIGHT" className="h-11 font-mono uppercase tracking-[.12em] placeholder:text-primary/70" maxLength={12} /></Field><Field label="Betting closes"><Input type="datetime-local" value={closesAt} onChange={(e) => setClosesAt(e.target.value)} className="h-11 [color-scheme:dark]" /></Field></div><Field label="Possible scenarios"><div className="grid gap-2">{labels.map((label, index) => <div className="flex gap-2" key={index}><span className="grid size-11 shrink-0 place-items-center rounded-xl text-xs font-bold" style={{ background: `${COLORS[index % COLORS.length]}18`, color: COLORS[index % COLORS.length] }}>{String.fromCharCode(65 + index)}</span><Input value={label} onChange={(e) => setLabels(labels.map((item, i) => i === index ? e.target.value : item))} placeholder={index === 0 ? 'First outcome' : 'Another outcome'} className="h-11" />{labels.length > 2 && <Button type="button" variant="ghost" size="icon" className="h-11" onClick={() => setLabels(labels.filter((_, i) => i !== index))}><X /></Button>}</div>)}<Button type="button" variant="outline" className="mt-1 justify-start" disabled={labels.length >= 6} onClick={() => setLabels([...labels, ''])}><Plus /> Add scenario</Button></div></Field></div>{error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}<Button type="submit" className="mt-7 h-12 w-full rounded-xl">Open bet <ArrowRight /></Button></form></section>;
}
