'use client';

import { useMemo } from 'react';
import {
  Activity, ArrowRight, Check, CircleDollarSign, Copy, Crown, LogOut, Radio, TrendingUp, X,
} from 'lucide-react';
import { Area, AreaChart, CartesianGrid, Tooltip, XAxis, YAxis } from 'recharts';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ChartContainer, ChartTooltipContent, type ChartConfig } from '@/components/ui/chart';
import { type ActivityItem, type Market, type Player, type Session, STARTING_BALANCE, odds } from './types';

export function RoomView({ session, market, players, activity, connection, selected, setSelected, amount, setAmount, placeTrade, copyInvite, copied, leave, error }: { session: Session; market: Market | null; players: Player[]; activity: ActivityItem[]; connection: string; selected: string; setSelected: (v: string) => void; amount: number; setAmount: (v: number) => void; placeTrade: () => void; copyInvite: () => void; copied: boolean; leave: () => void; error: string }) {
  const me = players.find((item) => item.name === session.username);
  const chartConfig = useMemo(() => Object.fromEntries((market?.outcomes || []).map((item) => [item.id, { label: item.label, color: item.color }])) as ChartConfig, [market]);
  if (!market) return <main className="grid min-h-screen place-items-center bg-background px-5"><div className="text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-primary/10 text-primary"><Radio className="size-6 animate-pulse" /></span><h1 className="mt-5 text-2xl font-semibold">Connecting to bet {session.roomCode}</h1><p className="mt-2 text-sm text-muted-foreground">Waiting for a secure peer connection…</p>{error && <p className="mt-4 text-sm text-destructive">{error}</p>}<Button onClick={leave} variant="outline" className="mt-6">Back home</Button></div></main>;
  return <main className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-20 border-b bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-3 px-4 py-3 md:px-7"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground shadow-[0_0_24px_rgba(40,209,124,.18)]"><Radio className="size-4" /></span><div><p className="text-sm font-semibold">Master Better</p><p className="text-[11px] text-muted-foreground">Bet {session.roomCode}</p></div></div><div className="flex items-center gap-2"><span className={`hidden items-center gap-1.5 rounded-full px-3 py-1.5 text-xs sm:flex ${connection === 'live' ? 'bg-primary/10 text-primary' : 'bg-secondary text-muted-foreground'}`}><span className={`size-1.5 rounded-full ${connection === 'live' ? 'bg-primary' : 'bg-muted-foreground'}`} />{connection === 'live' ? 'Peer sync live' : connection}</span><Button variant="outline" onClick={copyInvite}>{copied ? <Check /> : <Copy />}{copied ? 'Copied' : 'Invite'}</Button><Button variant="ghost" size="icon" onClick={leave}><LogOut /></Button></div></div></header>
    <div className="mx-auto grid max-w-[1500px] gap-4 p-4 md:p-7 lg:grid-cols-[240px_minmax(0,1fr)_290px]">
      <aside className="order-2 rounded-2xl border bg-card p-4 lg:order-1"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Players</p><span className="rounded-full bg-secondary px-2 py-1 text-[10px] font-bold">{players.length}</span></div><div className="mt-4 grid gap-2">{players.map((player) => <div key={player.name} className={`rounded-xl p-3 ${player.name === session.username ? 'bg-primary/10' : 'bg-background'}`}><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-full bg-secondary text-xs font-bold text-secondary-foreground">{player.name.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{player.name} {player.host && <Crown className="ml-1 inline size-3 text-[#d58d3d]" />}</p><p className="font-mono text-xs text-muted-foreground">${Math.round(player.balance).toLocaleString()}</p></div></div></div>)}</div><div className="mt-5 border-t pt-4"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Recent activity</p><div className="mt-3 grid gap-3">{activity.slice(0, 5).map((item) => <div key={item.id} className="flex gap-2 text-xs leading-5"><Activity className="mt-0.5 size-3.5 shrink-0 text-primary" /><p><span>{item.text}</span><span className="block text-[10px] text-muted-foreground">{item.time}</span></p></div>)}</div></div></aside>
      <section className="order-1 min-w-0 lg:order-2"><div className="rounded-2xl border bg-card p-5 md:p-7"><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">Live market</p><h1 className="mt-2 max-w-3xl text-2xl font-semibold tracking-tight md:text-3xl">{market.title}</h1><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{market.outcomes.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} className={`rounded-2xl border p-4 text-left transition ${selected === item.id ? 'border-primary bg-primary/5 ring-2 ring-primary/10' : 'bg-background hover:border-primary/40'}`}><div className="flex items-start justify-between gap-3"><span className="text-sm font-medium">{item.label}</span><span className="text-2xl font-semibold tracking-tight" style={{ color: item.color }}>{odds(market.outcomes, item.id)}%</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full transition-all duration-500" style={{ width: `${odds(market.outcomes, item.id)}%`, background: item.color }} /></div><p className="mt-2 text-[11px] text-muted-foreground">${item.pool.toLocaleString()} backing this outcome</p></button>)}</div><div className="mt-8 rounded-2xl bg-background p-4 md:p-6"><div className="mb-4 flex items-end justify-between"><div><p className="text-sm font-semibold">Crowd confidence</p><p className="text-xs text-muted-foreground">Probability shifts after every trade</p></div><TrendingUp className="size-5 text-primary" /></div><ChartContainer config={chartConfig} className="h-[280px] w-full aspect-auto"><AreaChart data={market.history} margin={{ left: -18, right: 8, top: 8 }}><defs>{market.outcomes.map((item) => <linearGradient key={item.id} id={`fill-${item.id}`} x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={item.color} stopOpacity={.24}/><stop offset="95%" stopColor={item.color} stopOpacity={0}/></linearGradient>)}</defs><CartesianGrid vertical={false} strokeDasharray="4 4" /><XAxis dataKey="tick" tickLine={false} axisLine={false} /><YAxis domain={[0, 100]} tickFormatter={(v) => `${v}%`} tickLine={false} axisLine={false} /><Tooltip content={<ChartTooltipContent />} />{market.outcomes.map((item) => <Area key={item.id} type="monotone" dataKey={item.id} stroke={item.color} fill={`url(#fill-${item.id})`} strokeWidth={2.5} dot={market.history.length < 3} animationDuration={350} />)}</AreaChart></ChartContainer></div></div></section>
      <aside className="order-3"><div className="sticky top-24 rounded-2xl border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Your position</p><span className="flex items-center gap-1 text-sm font-semibold text-primary"><CircleDollarSign className="size-4" />${Math.round(me?.balance ?? STARTING_BALANCE).toLocaleString()}</span></div><h2 className="mt-5 text-lg font-semibold">Back an outcome</h2><div className="mt-4 grid gap-2">{market.outcomes.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} className={`flex items-center justify-between rounded-xl border px-3 py-3 text-sm ${selected === item.id ? 'border-primary bg-primary/5' : 'bg-background'}`}><span className="flex items-center gap-2"><span className="size-2.5 rounded-full" style={{ background: item.color }} />{item.label}</span><span className="font-mono text-xs">{odds(market.outcomes, item.id)}¢</span></button>)}</div><label className="mt-5 block text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Amount</label><div className="relative mt-2"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">$</span><Input type="number" min={1} max={Math.floor(me?.balance ?? STARTING_BALANCE)} value={amount} onChange={(e) => setAmount(Number(e.target.value))} className="h-12 pl-7 font-mono text-base" /></div><div className="mt-2 grid grid-cols-4 gap-1">{[100, 500, 2500, 10000].map((value) => <Button key={value} variant="outline" size="sm" onClick={() => setAmount(value)}>${value}</Button>)}</div><Button onClick={placeTrade} disabled={!selected || amount <= 0 || amount > (me?.balance ?? STARTING_BALANCE) || connection !== 'live' && session.role === 'guest'} className="mt-5 h-12 w-full rounded-xl">Place prediction <ArrowRight /></Button><p className="mt-3 text-center text-[11px] leading-5 text-muted-foreground">Play money only. No real currency or prizes.</p><div className="mt-5 border-t pt-4"><p className="text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Your holdings</p><div className="mt-3 grid gap-2">{market.outcomes.filter((item) => (me?.holdings[item.id] || 0) > 0).map((item) => <div key={item.id} className="flex justify-between text-xs"><span>{item.label}</span><span className="font-mono">{(me?.holdings[item.id] || 0).toFixed(1)} shares</span></div>)}{!Object.values(me?.holdings || {}).some(Boolean) && <p className="text-xs text-muted-foreground">No positions yet.</p>}</div></div></div></aside>
    </div>
  </main>;
}
